Fix ansible-lint
Downgrade test container to avoid this which just appeared on the bleeding edge:

```
RuntimeError: Python 3.14 requires ansible-core version >= 2.20.0, and we found 2.19.3
```